Add a new filter type: "simple"
istio-ecosystem/authservice pull request #139
Opened 2021-03-24 08:54 UTC by ipuustin

Add a "simple" filter type. The filter approves or denies requests based on configuration value. The benefit of this is twofold:

1. Allow AuthService to run without OIDC providers. This can be needed if the AuthService configuration is dynamically constructed and may sometimes be without any OIDC chains.
2. Allow testing of external authorization logic in the cluster without having to introduce and configure OIDC providers.

Also, this helps to keep the filter abstraction in working shape by preventing configuration validation etc. getting tied to OIDC.

2021-03-24 08:54 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio-ecosystem/authservice/pull/139#" title="Author self-approved">ipuustin</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **sawlanipradeep** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @sawlanipradeep` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=istio-ecosystem%2Fauthservice).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/istio-ecosystem/authservice/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["sawlanipradeep"]} -->

2021-03-24 15:07 UTC, Shikugawa requested changes
Thanks! It generally LGTM but `simple` name is ambiguous a bit. Could you rename it? I think `mock` should be better.

2021-03-24 15:07 UTC, Shikugawa commented on src/filters/filter_chain.cc
> +      result->AddFilter(FilterPtr(new simple::SimpleFilter(filter.simple())));
nit: `std::make_unique<SimpleFilter>(filter.simple())`

2021-03-24 15:07 UTC, Shikugawa commented on test/filters/filter_chain_test.cc
> +  auto configuration =
nit: `make_unique`

2021-03-24 15:07 UTC, istio-testing commented
@Shikugawa: changing LGTM is restricted to collaborators

<details>

In response to [this](https://github.com/istio-ecosystem/authservice/pull/139#pullrequestreview-619832510):

>Thanks! It generally LGTM but `simple` name is ambiguous a bit. Could you rename it? I think `mock` should be better.


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-03-24 17:57 UTC, ipuustin commented
@Shikugawa thanks for the review! I implemented the changes you requested.

2021-03-25 02:22 UTC, Shikugawa commented
@ipuustin LGTM. Could you rewrite PR title into `Add a new filter type: "mock"`?

2021-03-25 08:13 UTC, Shikugawa commented
/approve

2021-03-25 08:13 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio-ecosystem/authservice/pull/139#" title="Author self-approved">ipuustin</a>*, *<a href="https://github.com/istio-ecosystem/authservice/pull/139#issuecomment-806454026" title="Approved">Shikugawa</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **sawlanipradeep** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @sawlanipradeep` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=istio-ecosystem%2Fauthservice).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/istio-ecosystem/authservice/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["sawlanipradeep"]} -->

2021-03-25 08:14 UTC, Shikugawa commented
ping @lizan

2021-03-31 04:42 UTC, lizan approved these changes

2021-03-31 04:42 UTC, istio-testing commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/istio-ecosystem/authservice/pull/139#" title="Author self-approved">ipuustin</a>*, *<a href="https://github.com/istio-ecosystem/authservice/pull/139#pullrequestreview-624886507" title="Approved">lizan</a>*, *<a href="https://github.com/istio-ecosystem/authservice/pull/139#issuecomment-806454026" title="Approved">Shikugawa</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=istio-ecosystem%2Fauthservice).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/istio-ecosystem/authservice/blob/master/OWNERS)~~ [lizan]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-03-31 04:43 UTC, merged